export enum EOrderStatus {
  PENDING='PENDING',
  PREPARING='PREPARING',
  DELIVERING='DELIVERING',
  DONE='DONE',
  CANCELLED_BY_COMPANY='CANCELLED_BY_COMPANY',
  CANCELLED_BY_CLIENT='CANCELLED_BY_CLIENT',
}
